coverage:
    status:
        patch:
            default:
                target: 80%
                threshold: 5%
        project:
            default:
                target: 80%
                threshold: 5%
    range: 70..100
    round: down
    precision: 2
ignore:
    - docs
comment:
    layout: diff, files