name: Make a new release
on:
    workflow_dispatch:
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
                  fetch-depth: 0
                  ref: ${{ github.ref_name }}
                  token: ${{ secrets.GH_ACCESS_TOKEN }}
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Github registry login
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/setup-go@v5
              with:
                go-version: '>=1.17.0'
            - name: set NODE_AUTH_TOKEN env
              run: echo "NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
            - name: set NPM_TOKEN env
              run: echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v4
              id: semantic
              with:
                  tag_format: ${version}
                  extra_plugins: |
                      @semantic-release/changelog@6.0.0
                      @semantic-release/npm,
                      @semantic-release/git
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: set VERSION env
              run: echo "VERSION=${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_ENV